"""add user profile fields

Revision ID: bc89dea5ec0a
Revises: 33b1d5f2a9c1
Create Date: 2026-03-23 15:21:18.330742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc89dea5ec0a'
down_revision: Union[str, Sequence[str], None] = '33b1d5f2a9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_overlap_events')
    op.drop_index(op.f('ix_bookings_guest_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_venue_id'), table_name='bookings')
    op.drop_index(op.f('ix_cancellation_events_actor_user_id'), table_name='cancellation_events')
    op.drop_index(op.f('ix_cancellation_events_booking_id'), table_name='cancellation_events')
    op.drop_index(op.f('ix_disputes_booking_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_payments_stripe_refund_id'), table_name='payments')
    op.create_unique_constraint(None, 'payments', ['stripe_refund_id'])
    op.add_column('reviews', sa.Column('role', sa.String(length=32), nullable=False))
    op.add_column('reviews', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('visible_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reviews', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_reviews_visible_at'), 'reviews', ['visible_at'], unique=False)
    op.drop_constraint(op.f('stripe_connected_accounts_user_id_key'), 'stripe_connected_accounts', type_='unique')
    op.create_index(op.f('ix_stripe_connected_accounts_user_id'), 'stripe_connected_accounts', ['user_id'], unique=True)
    op.drop_constraint(op.f('uq_stripe_webhook_events_event_id'), 'stripe_webhook_events', type_='unique')
    op.drop_index(op.f('ix_stripe_webhook_events_event_id'), table_name='stripe_webhook_events')
    op.create_index(op.f('ix_stripe_webhook_events_event_id'), 'stripe_webhook_events', ['event_id'], unique=True)
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=160), nullable=True))
    op.alter_column('venues', 'venue_category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('venues', 'venue_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('venues', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('venues', 'venue_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('venues', 'venue_category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_stripe_webhook_events_event_id'), table_name='stripe_webhook_events')
    op.create_index(op.f('ix_stripe_webhook_events_event_id'), 'stripe_webhook_events', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('uq_stripe_webhook_events_event_id'), 'stripe_webhook_events', ['event_id'])
    op.drop_index(op.f('ix_stripe_connected_accounts_user_id'), table_name='stripe_connected_accounts')
    op.create_unique_constraint(op.f('stripe_connected_accounts_user_id_key'), 'stripe_connected_accounts', ['user_id'])
    op.drop_index(op.f('ix_reviews_visible_at'), table_name='reviews')
    op.alter_column('reviews', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('reviews', 'visible_at')
    op.drop_column('reviews', 'is_public')
    op.drop_column('reviews', 'role')
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_index(op.f('ix_payments_stripe_refund_id'), 'payments', ['stripe_refund_id'], unique=True)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_index(op.f('ix_disputes_booking_id'), 'disputes', ['booking_id'], unique=False)
    op.create_index(op.f('ix_cancellation_events_booking_id'), 'cancellation_events', ['booking_id'], unique=False)
    op.create_index(op.f('ix_cancellation_events_actor_user_id'), 'cancellation_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_bookings_venue_id'), 'bookings', ['venue_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_guest_user_id'), 'bookings', ['guest_user_id'], unique=False)
    op.create_table('host_overlap_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('overlap_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('host_overlap_events_booking_id_fkey')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('host_overlap_events_venue_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('host_overlap_events_pkey'))
    )
    # ### end Alembic commands ###
